version: 2
jobs:
  kinetic:
    docker:
      - image: autonomoustuff/docker-builds:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests
            catkin_test_results
    working_directory: ~/src

  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests
            catkin_test_results
    working_directory: ~/src

  dashing:
    docker:
      - image: autonomoustuff/docker-builds:dashing-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            rosdep update
            rosdep install --from-paths . --ignore-src -y
            cd ..
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            cd ..
            colcon build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name local_setup.bash | sort | head -1`
            cd ..
            colcon test
            colcon test-result
    working_directory: ~/src

  kinetic_release:
    docker:
      - image: autonomoustuff/docker-builds:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq && apt-get install -y dh-make python-bloom ruby
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            cd pacmod_msgs/
            bloom-generate rosdebian --os-name ubuntu --os-version xenial --ros-distro kinetic
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            deb-s3 upload -b autonomoustuff-devel-qa -c xenial --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

  melodic_release:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq && apt-get install -y dh-make python-bloom ruby
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            cd pacmod_msgs/
            bloom-generate rosdebian --os-name ubuntu --os-version bionic --ros-distro melodic
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            deb-s3 upload -b autonomoustuff-devel-qa -c bionic --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - kinetic
      - melodic
  aws_release:
    jobs:
      - kinetic_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only:
                - /devel/dbc_extra/
              ignore:
                - master
                - /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
      - melodic_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only:
                - /devel/dbc_extra/
              ignore:
                - master
                - /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
